#ifndef FONTMAP_H
#define FONTMAP_H

#include "text_include.h"
#include "math/vec2.h"
#include <string>
#ifdef _WIN32
#	include <unordered_map>
#else
#	include <tr1/unordered_map>
#endif

/** 
 * Autogenerated.
 *
 * static class for mapping UV coordinates and element dimensions.
 */
class FontMap {

public:
	static void getTerminalFont1_UV(std::tr1::unordered_map<std::string,GLfloat*> & uv_map);
	static void getTerminalFont1_DIM(std::tr1::unordered_map<std::string,Vec2f*> & dim_map);
};

#endif